TP-DesignPatter/Models/Adaptateur/Compte.cs
using System;
using System.Collections.Generic;
using TP_DesignPatter.Models.Adaptateur;

namespace TP_DesignPatter.Models
{
    public class Compte : ICompte
    {
        public Compte(String categorie)
        {
            Categorie = categorie;
        }

        public int ID { get; set; }
        public string Categorie { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string MotDePasse { get; set; }
        public DateTime DateCreation { get; set; }

        public string AfficherCompte()
        {
            return $"{this.Prenom} {this.Nom}";
        }
    }
}

TP-DesignPatter/Models/Adaptateur/CompteAdapter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_DesignPatter.Models.Adaptateur
{
    public class CompteAdapter : ICompte
    {
        private Compte _compte;

        public CompteAdapter(Compte compte)
        {
            _compte = compte;
        }

        public string AfficherCompte()
        {
            return _compte.AfficherCompte();
        }
    }
}

TP-DesignPatter/Models/Adaptateur/ICompte.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_DesignPatter.Models.Adaptateur
{
    public interface ICompte
    {
        String AfficherCompte();
    }
}

TP-DesignPatter/Models/Adaptateur/ListComptes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_DesignPatter.Models.Adaptateur
{
    public class ListComptes
    {
        public List<ICompte> _comptes;

        public ListComptes()
        {
            _comptes = new List<ICompte>() {
                new Compte("Admin")
            };
            /*Compte compte = new Compte("Admin");
            _comptes = new List<ICompte>()
            {
                new CompteAdapter(compte)
            };*/
        }
    }
}

TP-DesignPatter/Models/Builder/Droit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_DesignPatter.Models
{
    public class Droit
    {
        public Droit(String categorie)
        {
            Categorie = categorie;
        }

        public int ID { get; set; }
        public string Categorie { get; set; }
        public int IdCompte { get; set; }
    }
}

TP-DesignPatter/Models/Builder/DroitAdministrationBuilder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_DesignPatter.Models.Builder
{
    public class DroitAdministrationBuilder : DroitBuilder
    {
    }
}

TP-DesignPatter/Models/Builder/DroitBuilder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_DesignPatter.Models.Builder
{
    public class DroitBuilder
    {
    }
}

TP-DesignPatter/Models/Builder/DroitGestionBuilder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_DesignPatter.Models.Builder
{
    public class DroitGestionBuilder : DroitBuilder
    {
    }
}

TP-DesignPatter/Models/Builder/DroitViewerBuilder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP_DesignPatter.Models.Builder
{
    public class DroitViewerBuilder : DroitBuilder
    {

    }
}

TP-DesignPatter/Controllers/CompteController.cs
using System.Web.Mvc;
using TP_DesignPatter.Models;
using TP_DesignPatter.Models.Adaptateur;

namespace TP_DesignPatter.Controllers
{
    public class CompteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TableComptes()
        {
            /*ListComptes list = new ListComptes();
            var Comptes = list._comptes.Where(c => c.Equals("Admin")).OrderBy(c => c.AfficherCompte()).ToList();*/

            return View();
        }
        public ActionResult Create()
        {
        /* Banque banque = new Banque();
            CompteUserBuilder = new CompteUserBuilder();

            banque.Construct(CompteUserBuilder); */

            return View();
        }

        public ActionResult Edit(int? id)
        {
            return View();
        }

        public ActionResult Delete(int? id)
        {
            return View();
        }
    }
}

TP-DesignPatter/Views/Compte/Create.cshtml
@model TP_DesignPatter.Models.Compte

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="min-h-screen flex items-center justify-center">

        <!-- login form -->
        <div class="bg-white max-w-lg p-16 rounded shadow-2xl w-2/3">

            <h2 class="text-3xl text-center font-bold mb-10 text-gray-800">Crée votre compte</h2>

            
            <form class="space-y-5">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div>
                    <label class="block mb-1 font-bold text-gray-500">Nom</label>
                    @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "w-full border-2 border-gray-200 p-3 rounded outline-none transition duration-300 ease-in-out transform focus:border-green-400 focus:text-green-500" } })
                    @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                </div>

                <div>
                    <label class="block mb-1 font-bold text-gray-500">Prenom</label>
                    @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "w-full border-2 border-gray-200 p-3 rounded outline-none transition duration-300 ease-in-out transform focus:border-green-400 focus:text-green-500" } })
                    @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
                </div>

                <div>
                    <label class="block mb-1 font-bold text-gray-500">Adresse mail</label>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "w-full border-2 border-gray-200 p-3 rounded outline-none transition duration-300 ease-in-out transform focus:border-green-400 focus:text-green-500" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>

                <div>
                    <label class="block mb-1 font-bold text-gray-500">Mot de passe</label>
                    @Html.PasswordFor(model => model.MotDePasse, new { @class = "w-full border-2 border-gray-200 p-3 rounded outline-none transition duration-300 ease-in-out transform focus:border-green-400 focus:text-green-500" })
                    @Html.ValidationMessageFor(model => model.MotDePasse, "", new { @class = "text-danger" })
                </div>

                <div>
                    <label class="block mb-1 font-bold text-gray-500">Retapez le mot de passe</label>
                    @Html.PasswordFor(model => model.MotDePasse, new { @class = "w-full border-2 border-gray-200 p-3 rounded outline-none transition duration-300 ease-in-out transform focus:border-green-400 focus:text-green-500" })
                    @Html.ValidationMessageFor(model => model.MotDePasse, "", new { @class = "text-danger" })
                </div>

                <div class="flex items-center">
                    <input type="checkbox" id="agree" style="position: relative;bottom: 5px">
                    <label for="agree" class="ml-2 text-gray-700 text-sm">J'accepte les conditions d'utilisations et la politique de confidentialité.</label>
                </div>

                <input type="submit" value="Crée mon compte" class="block w-full bg-green-400 hover:bg-green-500 transition duration-700 ease-in-out rounded transform hover:-translate-x-0 hover:scale-110 p-4 rounded text-green-800 hover:text-green-900" />
            </form>

        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP-DesignPatter/Views/Compte/Edit.cshtml
@model TP_DesignPatter.Compte

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Compte</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.motDePasse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.motDePasse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.motDePasse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateCreation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateCreation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateCreation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP-DesignPatter/Views/Compte/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<<div class="flex flex-col items-center justify-center bg-green-500 backgroundIndex">
    <h1 class="text-green-900 text-center" style="margin-top: 11vw">Bienvenue sur gestionaire d'ulisateur<br /> le plus puissant du marché !</h1>
    <span class="bg-green-500">@Html.ActionLink("Nous rejoindre", "Create", "Compte")</span>
</div>

 <div class="flex flex-col m-auto p-auto justify-center" style="margin-top: 4vw">

     <div class="flex justify-center">
         <div class="flex flex-nowrap">
             <div class="inline-block" style="margin-right: 5vw">
                 <div class=" px-8 py-8 bg-white overflow-hidden rounded-lg shadow-md bg-white hover:shadow-xl transition-shadow duration-300 ease-in-out" style="border-left: solid #10b981 3px;">

                     <h3 class="py-2 text-4xl font-bold font-sans" style="margin-top:0"><i class="fas fa-clock text-4xl text-green-500"></i> OptiReponse®</h3>
                     <p class="text-xl">En moyenne le temps de réponse est de 0.3 ms <br /> Grâce à notre technique brevetée</p>

                 </div>
             </div>
             <div class="inline-block" style="margin-right: 5vw">
                 <div class=" px-8 py-8 bg-white overflow-hidden rounded-lg shadow-md bg-white hover:shadow-xl transition-shadow duration-300 ease-in-out" style="border-left: solid #10b981 3px;">

                     <h3 class="py-2 text-4xl font-bold font-sans" style="margin-top:0"><i class="fas fa-server text-4xl text-green-500"></i> Disponibilité</h3>
                     <p class="text-xl">Nos infrastructures sont sécurisées et répliquées partout dans le monde <br /> Ce qui nous garantit une haute disponibilité</p>

                 </div>
             </div>
             <div class="inline-block">
                 <div class=" px-8 py-8 bg-white overflow-hidden rounded-lg shadow-md bg-white hover:shadow-xl transition-shadow duration-300 ease-in-out" style="border-left: solid #10b981 3px;">

                     <h3 class="py-2 text-4xl font-bold font-sans" style="margin-top:0"><i class="fas fa-ticket-alt text-4xl text-green-500"></i> Support 24h/24h</h3>
                     <p class="text-xl">Il est primordial pour nous de vous épauler au quotidien <br /> Grâce à plusieurs plates-formes à travers le monde</p>

                 </div>
             </div>
         </div>
     </div>
 </div>

<style>
    .backgroundIndex {
        background-image: url(https://i.imgur.com/iQUxJmS.png);
        background-repeat: no-repeat;
        background-size: 31vw;
        background-position-x: 50px;
        height: 32vw;
        border-bottom: solid #064e3b 6px;
    }


    span {
        position: relative;
        display: inline-flex;
        width: 180px;
        height: 55px;
        margin: 50px 15px;
    }

        span a {
            font-size: 19px;
            letter-spacing: 1px;
            transform-style: preserve-3d;
            transform: translateZ(-25px);
            transition: transform .25s;
            font-family: 'Montserrat', sans-serif;
        }

            span a:before,
            span a:after {
                position: absolute;
                content: "Nous rejoindre";
                height: 55px;
                width: 180px;
                display: flex;
                align-items: center;
                justify-content: center;
                border: 3px solid black;
                box-sizing: border-box;
                border-radius: 10px;
            }

            span a:before {
                color: #fff;
                background: #000;
                transform: rotateY(0deg) translateZ(25px);
            }

            span a:after {
                color: #000;
                transform: rotateX(90deg) translateZ(25px);
            }

            span a:hover {
                transform: translateZ(-25px) rotateX(-90deg);
            }
</style>

TP-DesignPatter/Views/Compte/TableComptes.cshtml
@model TP_DesignPatter.Models.Adaptateur.ListComptes

@{
    ViewBag.Title = "TableComptes";
}

<div class="antialiased font-sans">
    <div class=" mx-auto px-4 sm:px-8">
        <div class="py-8">
            <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto" style="padding: 50px;margin-top: 50px">
                <div class="inline-block min-w-full shadow-md rounded-lg overflow-hidden"
                     style="border: solid 1px #d0d0d0;">
                    <table class="min-w-full leading-normal">
                        <thead>
                            <tr>
                                <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Utilisateurs
                                </th>
                                <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Categorie
                                </th>
                                <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Date de création
                                </th>
                                <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Actions
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @*@foreach (var compte in Model._comptes)
                            {*@
                                <tr>
                                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-lg">
                                        <div class="flex items-center">
                                            <div class="ml-3">
                                                <p class="text-gray-900 whitespace-no-wrap">
                                                    @*@compte.nom @compte.prenom*@
                                                </p>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-lg">
                                        <p class="text-gray-900 whitespace-no-wrap">@*@compte.categorie*@</p>
                                    </td>
                                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-lg">
                                        <p class="text-gray-900 whitespace-no-wrap">
                                            @*@compte.dateCreation*@
                                        </p>
                                    </td>
                                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">

                                        <span style="padding: 2px 6px 3px 6px; margin-right:5px"
                                              class="font-bold bg-yellow-200 text-yellow-900 rounded-full ">
                                            @*@Html.ActionLink("Modifier",
                                                "Modification", "Compte", new { id = compte.Id })*@
                                        </span>
                                        <span style="padding: 2px 6px 3px 6px;"
                                              class="font-bold bg-red-200 text-red-900 rounded-full ">
                                            @*@Html.ActionLink("Supprier",
                                                "Modification", "Compte", new { id = compte.Id })*@
                                        </span>

                                    </td>
                                </tr>
                            @*}*@
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

TP-DesignPatter/Views/Compte/View.cshtml
@model TP_DesignPatter.Compte

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Compte</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.motDePasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.motDePasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateCreation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateCreation)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TP-DesignPatter/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TP-DesignPatter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/0.0.0-insiders.4a070ac/tailwind.min.css" integrity="sha512-vJu7D5BpjnNXVpLBrl9LKLvmXBNjiLwge8EOZ/YS9XwiChpfKLAlydwIZvoJaDE3LI/kr3goH0MzDzNbBgyoOQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="font-sans">
    <div class="navbar navbar-inverse navbar-fixed-top shadow-lg">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SuperUsers", "Index", "Compte", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="transition duration-300">@Html.ActionLink("Gèrer mon compte", "TableComptes", "Compte")</li>
                    <li class="RegistrationBtn bg-green-500 hover:bg-green-600 transition duration-700 ease-in-out rounded transform hover:-translate-x-0 hover:scale-110 text-green-800 hover:text-green-900">@Html.ActionLink("Nous rejoindre", "Create", "Compte")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="bg-gray-100 FullSize">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <style>
        .FullSize {
            position: absolute;
            right: 0;
            left: 0;
            bottom: 0;
            top: 0;
        }

        .RegistrationBtn {
            position: absolute !important;
            right: 20px;
            top: 9px;
        }

            .RegistrationBtn > a {
                padding: 4px 22px 7px !important;
                color: rgba(6,95,70) !important;
            }
    </style>
</body>
</html>